# Generated by Django 6.0.6 on 2026-06-08 15:15

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import parler.fields
import parler.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('access_level', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='intermundane.accesslevel')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=255)),
                ('image_link', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('access_level', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='intermundane.accesslevel')),
            ],
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intermundane.character')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('name', 'Name'), ('about', 'About'), ('powers', 'Powers'), ('chapter', 'Chapter'), ('youtube', 'Youtube')], default='chapter', max_length=50)),
                ('unlock_type', models.CharField(choices=[('gte', 'Greater/equal level'), ('e', 'Equal level'), ('lt', 'Less level'), ('k', 'Content block')], default='gte', max_length=50)),
                ('sequence', models.IntegerField(default=0)),
                ('image_link', models.CharField(blank=True, max_length=255, null=True)),
                ('access_level', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='intermundane.accesslevel')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_blocks', to='intermundane.character')),
                ('content_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intermundane.contentblock')),
            ],
            options={
                'ordering': ['sequence'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input', models.CharField(max_length=255, unique=True)),
                ('action', models.CharField(choices=[('say', 'Say'), ('redirect', 'Redirect'), ('promote', 'Promote'), ('unlock', 'Unlock')], max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('access_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intermundane.accesslevel')),
                ('content_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intermundane.contentblock')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('access_level', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='intermundane.accesslevel')),
            ],
        ),
        migrations.AddField(
            model_name='contentblock',
            name='world',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intermundane.world'),
        ),
        migrations.AddField(
            model_name='character',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intermundane.world'),
        ),
        migrations.CreateModel(
            name='WorldContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('about', 'About'), ('chapter', 'Chapter'), ('title', 'Title')], default='chapter', max_length=50)),
                ('unlock_type', models.CharField(choices=[('gte', 'Greater/equal level'), ('e', 'Equal level'), ('lt', 'Less level'), ('k', 'Content block')], default='gte', max_length=50)),
                ('sequence', models.IntegerField(default=0)),
                ('image_link', models.CharField(blank=True, max_length=255, null=True)),
                ('access_level', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='intermundane.accesslevel')),
                ('content_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intermundane.contentblock')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_blocks', to='intermundane.world')),
            ],
            options={
                'ordering': ['sequence'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WorldContentBlockTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='intermundane.worldcontentblock')),
            ],
            options={
                'verbose_name': 'world content block Translation',
                'db_table': 'intermundane_worldcontentblock_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AccessLevelTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=255)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='intermundane.accesslevel')),
            ],
            options={
                'verbose_name': 'access level Translation',
                'db_table': 'intermundane_accesslevel_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('language_code', 'master'), name='intermundane_accesslevel_translation_uniq_lang')],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CharacterContentBlockTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='intermundane.charactercontentblock')),
            ],
            options={
                'verbose_name': 'character content block Translation',
                'db_table': 'intermundane_charactercontentblock_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('language_code', 'master'), name='intermundane_charactercontentblock_translation_uniq_lang')],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ResponseTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('response', models.CharField(max_length=255)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='intermundane.response')),
            ],
            options={
                'verbose_name': 'response Translation',
                'db_table': 'intermundane_response_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('language_code', 'master'), name='intermundane_response_translation_uniq_lang')],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked', models.DateTimeField(auto_now_add=True)),
                ('content_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intermundane.contentblock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'content_key')},
            },
        ),
        migrations.AddConstraint(
            model_name='contentblock',
            constraint=models.CheckConstraint(condition=models.Q(('character__isnull', False), ('world__isnull', False), _connector='OR'), name='requires_character_or_world'),
        ),
        migrations.AddConstraint(
            model_name='worldcontentblocktranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='intermundane_worldcontentblock_translation_uniq_lang'),
        ),
    ]
