# Generated by Django 6.0.6 on 2026-06-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intermundane", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactercontentblock",
            name="css_class",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="worldcontentblock",
            name="css_class",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
