from django.shortcuts import render, redirect

from ..models import Response, UserProgress, AuditLog, AccessLevel

# functionality for ARG progression and index page
def index(request):
    if request.method != "POST": # == Get
        return render(request, "intermundane/index.html")

        # checks if user is registered
    if not request.user.is_authenticated:
        return render(request, "intermundane/index.html", {"error":"need-login"})

        # checks if response exists
        # for input, the case is ingored, spaces are replaced with '-' to match response code in database
    response = Response.objects.filter(user_input = request.POST["code"].lower().strip().replace(' ', '-')).first()
    if not response:
        return render(request, "intermundane/index.html", {"error":"no-code"})

        # checks if user has valid access level for this response
    user_level = request.user.access_level.level
    if response.access_level and user_level < response.access_level.level:
        return render(request, "intermundane/index.html", {"error":"early-code"})

        # redirects user to another page
    if response.action=="redirect":
        return redirect(response.response)

        # increases user access level to next one (does nothing if user is already at higher access level)
    if response.action=="promote":
        if user_level == response.access_level.level:
            request.user.access_level = AccessLevel.objects.get(level=user_level+1)
            request.user.save()
            log = AuditLog(
                user=request.user,
                source="arg",
                action=response.action+" level to: "+str(response.access_level.level+1)
            )
            log.save()

        # unlocks a content key if the user has not yet unlocked it before
    if response.action=="unlock":
        progress = UserProgress.objects.filter(user=request.user, content_key=response.content_block)
        if not progress:
            obj = UserProgress(
                user=request.user,
                content_key=response.content_block
            )
            obj.save()
            log = AuditLog(
                user=request.user,
                source="arg",
                action=response.action+" "+response.content_block.key
            )
            log.save()

        # renders answer that is generated by any type of response, including "Say"
    return render(request, "intermundane/index.html", {"response":response.response})